### ISSUE TITLE
support for libvirt and qemu

### ISSUE THREAD

**Issue by M0roSan** [systemdemo/workshop#1]
for mac M1/M2 users, this workshop can't be run reliably. 

Proposal 1:
supporting qemu in vagrant file and libvirt provider for [aleivag/fedora37](https://app.vagrantup.com/aleivag/boxes/fedora37)

**Comment by aleivag** [comment]
Thanks for reporting, yeap we saw this on our dry runs... we are looking at a couple of options, one its to provide a provisioning script, so people can bring their own fedora, the other its just to have a instance in linode... 

qemu as far as i know its not supported by vagrant, and there is no oficial libvirt image for fedora in vagrant... i'll post the solution here and in the docs

**Comment by M0roSan** [comment]
https://github.com/ppggff/vagrant-qemu is vagrant qemu plugin I was taking a look at. 

I haven't looked closely into the actual workshop item but if it's just a systemd service without touching any part of fedora, then some people might be able to bring any potential linux distro machines like debian-buster, ubuntu, etc.

Let me know if I can help you anyway or I'll see you on Friday

**Comment by aleivag** [comment]
I have added a section on how to bring your own machine: 
https://github.com/systemdemo/workshop/tree/main/workshop/GETTING_STARTED#hey-i-cant-run-your-virtualbox-what-now

you are right that fedora here is pseudo irrelevant, except, except that the provisioning script uses dnf and disable selinux and its the distro we tested this... 

people might bring their own distro... and we probably will make it work, key word been probably

thanks again for the help !
